### PR TITLE
force usage of shared_ptr for params as well

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by wolfv** [comment]
Hey @Evil-Spirit I have changed the params as well, to use a shared ptr. With this design we don't need a custom hash or equality function -- the param pointer is the unique ID to the param (I guess this is closer in spirit to the original C# code).

At some point we might want to check if we can reduce the overhead of having so many shared pointers but I guess it's fine for the moment.

**Comment by Evil-Spirit** [comment]
@wolfv The problem with using of too much Expression present in SolveSpace where equation rewrited every time while dragging point. In NoteCAD the different approach - we rewrite equations only when sketch topology changed (addition, removing, conincidence, etc), so the problems with slow allocation/deallocation is absent (almost). So, no need to write custom allocator/deallocator and probably using shared_ptr is ok.

**Comment by Evil-Spirit** [comment]
But still can be performance problem with Eval. I can't remember whether shaded_ptr access is zero cost or not.

**Comment by wolfv** [comment]
I think access cost should be zero, but copying, creation and deletion has some overhead obviously.

**Pull request merged**
